//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _23_LTUTD_NVG_MSV.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel;


    public partial class HoaDonBanSach
    {
        [Key]
        public int MaHD { get; set; }
        [StringLength(50, MinimumLength = 5)]
        public Nullable<int> MaSach { get; set; }
        public string KhachHang { get; set; }

        [DataType(DataType.DateTime)] // dữ liệu là ngày tháng năm
        /*
        [DataType(DataType.PhoneNumber)] // dữ liệu phải kiểu số điện thoại
        [DataType(DataType.EmailAddress)] // dữ liệu phải kiểu email
        [DataType(DataType.Password)] // dữ liệu phải kiểu pass(tức là hiển thị ra ký *)
        */
        public Nullable<System.DateTime> NgayBan { get; set; }

        [Range(1,int.MaxValue)]
        public Nullable<int> SoLuong { get; set; }

        public virtual Sach Sach { get; set; }
    }
}
