//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienBanKiemKe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BienBanKiemKe()
        {
            this.BienBanKiemKeChiTiets = new HashSet<BienBanKiemKeChiTiet>();
        }
    
        public int ID { get; set; }
        public string TenBienBan { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public int idNguoiLap { get; set; }
        public string TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BienBanKiemKeChiTiet> BienBanKiemKeChiTiets { get; set; }
    }
}
