//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienBanKiemKeChiTiet
    {
        public int ID { get; set; }
        public int idBienBan { get; set; }
        public int idLoaiSanPham { get; set; }
        public Nullable<double> SoLuongTonKho { get; set; }
        public Nullable<double> SoLuongThucTe { get; set; }
        public Nullable<double> ChenhLech { get; set; }
        public string LyDo { get; set; }
    
        public virtual BienBanKiemKe BienBanKiemKe { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
