//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHangban
    {
        public int ID { get; set; }
        public Nullable<int> idDonHangBan { get; set; }
        public Nullable<int> idSanPham { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<double> DonGiaApDung { get; set; }
        public Nullable<double> GiaTriGiamGia { get; set; }
        public Nullable<double> PhanTramGiamGia { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        public virtual DonHangBan DonHangBan { get; set; }
    }
}
