//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHangMua
    {
        public int ID { get; set; }
        public int idDonHangMua { get; set; }
        public int idLoaiSanPham { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<double> DonGiaNhap { get; set; }
        public Nullable<double> GiaTriGiamGia { get; set; }
        public Nullable<double> PhanTramGiamGia { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        public virtual DonHangMua DonHangMua { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
