//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuongTrinhGiamGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChuongTrinhGiamGia()
        {
            this.ChuongTrinhKhuyenMaiApDungs = new HashSet<ChuongTrinhKhuyenMaiApDung>();
        }
    
        public int ID { get; set; }
        public string TenChuongTrinh { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string DieuKienApDung { get; set; }
        public Nullable<int> idLoaiChuongTrinh { get; set; }
        public Nullable<double> SoTienGiam { get; set; }
        public Nullable<double> SoPhanTramGiamGia { get; set; }
    
        public virtual LoaiChuongTrinhGiamGia LoaiChuongTrinhGiamGia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChuongTrinhKhuyenMaiApDung> ChuongTrinhKhuyenMaiApDungs { get; set; }
    }
}
