//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuongTrinhKhuyenMaiApDung
    {
        public int ID { get; set; }
        public Nullable<int> idChuongTrinh { get; set; }
        public Nullable<int> idDonHang { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ChuongTrinhGiamGia ChuongTrinhGiamGia { get; set; }
        public virtual DonHangBan DonHangBan { get; set; }
    }
}
