//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHangMua
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHangMua()
        {
            this.ChiTietDonHangMuas = new HashSet<ChiTietDonHangMua>();
        }
    
        public int ID { get; set; }
        public Nullable<int> idNguongHang { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<double> GiaTriGiamGia { get; set; }
        public Nullable<int> idNhanVienLap { get; set; }
        public Nullable<double> TongTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHangMua> ChiTietDonHangMuas { get; set; }
        public virtual NguonHang NguonHang { get; set; }
    }
}
