//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHangBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHangBan()
        {
            this.ChiTietDonHangbans = new HashSet<ChiTietDonHangban>();
            this.ChuongTrinhKhuyenMaiApDungs = new HashSet<ChuongTrinhKhuyenMaiApDung>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<int> idNhanVienLap { get; set; }
        public Nullable<int> idKhachHang { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<int> idTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHangban> ChiTietDonHangbans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChuongTrinhKhuyenMaiApDung> ChuongTrinhKhuyenMaiApDungs { get; set; }
        public virtual TrangThaiDonHangBan TrangThaiDonHangBan { get; set; }
    }
}
