//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiSanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiSanPham()
        {
            this.BienBanKiemKeChiTiets = new HashSet<BienBanKiemKeChiTiet>();
            this.ChiTietDonHangMuas = new HashSet<ChiTietDonHangMua>();
        }
    
        public int ID { get; set; }
        public string TenSanPham { get; set; }
        public string MaVach { get; set; }
        public Nullable<double> GiaNiemYet { get; set; }
        public string DonViTinh { get; set; }
        public Nullable<double> GiaTriGiamGia { get; set; }
        public Nullable<double> PhanTramGiamGia { get; set; }
        public Nullable<int> idNhomSanPham { get; set; }
        public string NhaSanXuat { get; set; }
        public Nullable<System.DateTime> NgaySanXuat { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BienBanKiemKeChiTiet> BienBanKiemKeChiTiets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHangMua> ChiTietDonHangMuas { get; set; }
        public virtual NhomSanPham NhomSanPham { get; set; }
    }
}
