//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyBanHangEntities : DbContext
    {
        public QuanLyBanHangEntities()
            : base("name=QuanLyBanHangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BangLuong> BangLuongs { get; set; }
        public virtual DbSet<BienBanKiemKe> BienBanKiemKes { get; set; }
        public virtual DbSet<BienBanKiemKeChiTiet> BienBanKiemKeChiTiets { get; set; }
        public virtual DbSet<ChiTietDonHangban> ChiTietDonHangbans { get; set; }
        public virtual DbSet<ChiTietDonHangMua> ChiTietDonHangMuas { get; set; }
        public virtual DbSet<ChucNang> ChucNangs { get; set; }
        public virtual DbSet<ChuongTrinhGiamGia> ChuongTrinhGiamGias { get; set; }
        public virtual DbSet<ChuongTrinhKhuyenMaiApDung> ChuongTrinhKhuyenMaiApDungs { get; set; }
        public virtual DbSet<DonHangBan> DonHangBans { get; set; }
        public virtual DbSet<DonHangMua> DonHangMuas { get; set; }
        public virtual DbSet<DonViTinh> DonViTinhs { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LoaiChuongTrinhGiamGia> LoaiChuongTrinhGiamGias { get; set; }
        public virtual DbSet<LoaiSanPham> LoaiSanPhams { get; set; }
        public virtual DbSet<NguonHang> NguonHangs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<NhomSanPham> NhomSanPhams { get; set; }
        public virtual DbSet<PhanQuyenNhanVien> PhanQuyenNhanViens { get; set; }
        public virtual DbSet<PhuCap> PhuCaps { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TamUng> TamUngs { get; set; }
        public virtual DbSet<TheKhachHang> TheKhachHangs { get; set; }
        public virtual DbSet<TrangThaiDonHangBan> TrangThaiDonHangBans { get; set; }
        public virtual DbSet<TrangThaiDonHangMua> TrangThaiDonHangMuas { get; set; }
        public virtual DbSet<TruLuong> TruLuongs { get; set; }
    
        public virtual ObjectResult<DanhSachNhanVien_Result> DanhSachNhanVien(string key)
        {
            var keyParameter = key != null ?
                new ObjectParameter("key", key) :
                new ObjectParameter("key", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DanhSachNhanVien_Result>("DanhSachNhanVien", keyParameter);
        }
    }
}
