//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguonHang()
        {
            this.DonHangMuas = new HashSet<DonHangMua>();
        }
    
        public int ID { get; set; }
        public string TenNguonHang { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string SoDienThoai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string nguoiDaiDien { get; set; }
        public string STK { get; set; }
        public string NganHang { get; set; }
        public Nullable<bool> TrangThaiHopTac { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHangMua> DonHangMuas { get; set; }
    }
}
