//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheKhachHang
    {
        public int ID { get; set; }
        public string MaSoThe { get; set; }
        public Nullable<int> idKhachHang { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public string LoaiThe { get; set; }
        public Nullable<bool> TrangThaiHoatDong { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
