//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sach_phieumuon.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PhieuMuon
    {
        [Key]
        public int MaPhieu { get; set; }
        public Nullable<int> MaSach { get; set; }
        [StringLength(50, MinimumLength = 5)]
        public string NguoiMuon { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgayMuon { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgayTra { get; set; }

        public virtual Sach Sach { get; set; }
    }
}
