//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ontap3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ThietBi
    {
        [Key]
        public int MaTB { get; set; }
        [Required]
        public string TenTB { get; set; }
        [Required]

        public Nullable<int> SoLuong { get; set; }
        [Required]

        public Nullable<double> DonGia { get; set; }

        public Nullable<double> ThanhTien { get; set; }
        [Required]

        public Nullable<int> MaNCC { get; set; }
    
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
