//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ontap4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BenhNhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BenhNhan()
        {
            this.LichHens = new HashSet<LichHen>();
        }
        [Key]
        [Required]
        public int MaBN { get; set; }
        [Required]
        [StringLength(50, MinimumLength = 5)]
        public string HoTen { get; set; }
        [Required]
        [DisplayFormat(DataFormatString =("{dd:MM:yyyy}"), ApplyFormatInEditMode =true)]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgaySinh { get; set; }
        [Required]

        public string GioiTinh { get; set; }
        [Required]
        [MinLength(10)]
        [Phone]
        public string SDT { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichHen> LichHens { get; set; }
    }
}
