//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ontap4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.CompilerServices;

    public partial class LichHen
    {
        [Key]
        public int MaLichHen { get; set; }
        public Nullable<int> MaBN { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgayHen { get; set; }
        [StringLength(50, MinimumLength = 5)]
        public string BacSi { get; set; }
        public string LyDo { get; set; }

        public virtual BenhNhan BenhNhan { get; set; }
    }
}
