//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace De26.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HoaDonDatMon
    {
        [Key]
        public int MaHD { get; set; }
        public int MaMon { get; set; }
        public string KhachHang { get; set; }
        public System.DateTime NgayDat { get; set; }
        //[Range(1, MonAn.SoLuongTon)]
        public int SoLuong { get; set; }
    
        public virtual MonAn MonAn { get; set; }
    }
}
