//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _16_LTUDDN_NguyenVanGiang_21103101232_DHTI15A19HN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BenhNhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BenhNhan()
        {
            this.LichSuDieuTris = new HashSet<LichSuDieuTri>();
        }
        [Key]
        public int MaBN { get; set; }
        [Required]
        [StringLength(50, MinimumLength = 5)]
        public string HoTen { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgaySinh { get; set; }
        [Required]
        public Nullable<bool> GioiTinh { get; set; }
        [Required]

        public string SDT { get; set; }
        [Required]
        [MaxLength(100)]
        public string DiaChi { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuDieuTri> LichSuDieuTris { get; set; }
    }
}
