//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _16_LTUDDN_NguyenVanGiang_21103101232_DHTI15A19HN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LichSuDieuTri
    {
        [Key]
        public int MaLS { get; set; }
        public Nullable<int> MaBN { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgayDieuTri { get; set; }
        [MaxLength(100)]
        public string ChuanDoan { get; set; }
        [MaxLength(100)]
        public string PhuongPhap { get; set; }
        [Range(1,int.MaxValue)]
        public Nullable<decimal> ChiPhi { get; set; }
    
        public virtual BenhNhan BenhNhan { get; set; }
    }
}
