//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class docgia
    {
        public string madg { get; set; }
        public string tendg { get; set; }
        public string coquan { get; set; }
        public string diachi { get; set; }
        public string sdt { get; set; }
    }
}
